name: "Talos Pull Request Title"
description: "Beautify the PR Title"

inputs:
  repo-token:
    description: "Repo Token"
    required: true

runs:
  using: "composite"
  steps:
    - name: Call Action.
      run: |
        ${{ github.action_path }}/action.sh
      env:
        REPO_TOKEN: ${{ inputs.repo-token }}
        REPO_NAME: ${{ github.repository }}
        PR_NUMBER: ${{ github.event.number }}
      shell: bash
