name: "Talos Pull Request Title"
description: "Beautify the PR title"

outputs:
  jira_id:
    description: "Jira ID found in PR title or branch name."
    value: ${{ steps.update-title.outputs.jira_id }}

runs:
  using: "composite"
  steps:
    - name: Update title
      id: update-title
      run: ${{ github.action_path }}/action.sh
      env:
        REPO_TOKEN: ${{ github.token }}
        REPO_NAME: ${{ github.repository }}
        PR_NUMBER: ${{ github.event.number }}
        BRANCH_NAME: ${{ github.head_ref || github.ref_name }} # head ref is only set for PRs, fall back to ref_name otherwise
      shell: bash
